# Generated by Django 3.0.4 on 2020-03-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(max_length=3)),
                ('problem', models.TextField()),
                ('solution', models.TextField(null=True)),
                ('done_by', models.CharField(max_length=64)),
                ('supervised_by', models.CharField(max_length=64)),
                ('datestamp', models.DateField()),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
